### ISSUE TITLE
Failure to include in an email a previously attached file in a transaction

### ISSUE THREAD

**Issue by doloresjuliana** [doloresjuliana/pibiapp#5]
Traceback (most recent call last):
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/core/doctype/communication/email.py", line 86, in make
    add_attachments(comm.name, attachments)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/core/doctype/communication/email.py", line 410, in add_attachments
    "Home/Attachments", attach.is_private)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/utils/file_manager.py", line 102, in save_url
    f.insert();
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 242, in insert
    self.run_method("after_insert")
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 1011, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/erpnext/erpnext-prd/apps/pibiapp/pibiapp/nextcloud/nextcloud_link.py", line 133, in nextcloud_insert
    nc.webdav.upload(local_fileobj, remote_fileobj=fileobj[uu], nc_path=path)
  File "/home/erpnext/erpnext-prd/apps/pibiapp/pibiapp/nextcloud/nextcloud_apis.py", line 122, in upload
    with open(local_fileobj, 'rb') as fileobj:
IOError: [Errno 2] No such file or directory: u'./erp.eshttps://docs.es:4334/f/2815'

**Comment by doloresjuliana** [comment]
Problem solved in version 0.2.0 
https://github.com/doloresjuliana/pibiapp/commit/4b118d0760edc275ecdcb08f400252891ab55a3c
