### ISSUE TITLE
Error in attaching   for the second time the same file

### ISSUE THREAD

**Issue by doloresjuliana** [doloresjuliana/pibiapp#6]
Traceback (most recent call last):
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/handler.py", line 109, in uploadfile
    ret = frappe.utils.file_manager.upload()
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/utils/file_manager.py", line 36, in upload
    file_doc = get_file_doc()
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/utils/file_manager.py", line 70, in get_file_doc
    file_doc = save_url(r.file_url, r.filename, dt, dn, folder, is_private, df)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/utils/file_manager.py", line 102, in save_url
    f.insert();
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 242, in insert
    self.run_method("after_insert")
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 757, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 1026, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/erpnext/erpnext-prd/apps/frappe/frappe/model/document.py", line 1011, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "/home/erpnext/erpnext-prd/apps/pibiapp/pibiapp/nextcloud/nextcloud_link.py", line 154, in nextcloud_insert
    fileid = str(decoded["ocs"]["data"]["file_source"])
TypeError: list indices must be integers, not unicode

**Comment by doloresjuliana** [comment]
Problem solved in version 0.2.0 
https://github.com/doloresjuliana/pibiapp/commit/4b118d0760edc275ecdcb08f400252891ab55a3c
